version: '3.7'
services:
    backend:
        image: newsnet:latest
        volumes:
            - .:/srv/app
            - ./node_modules:/srv/app/node_modules
        command: npm run start:debug -- --preserveWatchOutput
        environment:
            NODE_ENV: development
            PORT: 3000
        ports:
            - 8080:3000
            - 9229:9229

