version: '3.7'
services:
  newshub-api-node:
    container_name: newshub-api-node
    build: ./api/node
    restart: always
    volumes:
      - ./api/node:/srv/app
      - /srv/app/node_modules/
    env_file:
      - ./api/node/.env
    depends_on:
      - newshub-api-python
    command: npm run start:debug -- --preserveWatchOutput
    ports:
      - "3000:3000"

  newshub-api-python:
    container_name: newshub-api-python
    build: ./api/python
    restart: always
    volumes:
      - ./api/python:/app
      - /app/venv/lib/python3.10/site-packages/
    env_file:
      - ./api/python/.env
    ports:
      - "4000:4000"

