version: "3.7"
services:
  api-node:
    container_name: api-node
    build: ./api/node
    restart: always
    volumes:
      - ./api/node:/srv/app
      - /srv/app/node_modules/
    env_file:
      - ./api/node/.env
    depends_on:
      - api-python
    command: npm run start:debug -- --preserveWatchOutput
    ports:
      - "3000:3000"

  api-python:
    container_name: api-python
    build: ./api/python
    restart: always
    volumes:
      - ./api/python:/app
      - /app/venv/lib/python3.10/site-packages/
    env_file:
      - ./api/python/.env
    ports:
      - "4000:4000"

  browser-extension:
    container_name: browser-extension
    build: ./apps/browser_extension
    restart: always
    depends_on:
      - api-node
    volumes:
      - ./apps/browser_extension:/srv/app


  admin-dashboard:
    container_name: admin-dashboard
    build: ./apps/dashboard
    restart: always
    depends_on:
      - api-node
    volumes:
      - ./apps/dashboard:/app
      - /app/node_modules/
    ports:
      - "3001:3001"
